/*
 * This source file was generated by the Gradle 'init' task
 */
package daigle_catherine.assignment2;

/* */
import com.microsoft.azure.sdk.iot.device.*;
import com.microsoft.azure.sdk.iot.device.exceptions.IotHubClientException;
import com.microsoft.azure.sdk.iot.device.transport.IotHubConnectionStatus;
/* */

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        // TODO set up connection
        // TODO set up messages
        // TODO send messages
    }

    /**
     * Referenced from {@link https://github.com/Azure/azure-iot-sdk-java/blob/main/iothub/device/iot-device-samples/send-receive-module-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SendReceiveModuleSample.java}
     */
    protected static class IotHubConnectionStatusChangeCallbackLogger implements IotHubConnectionStatusChangeCallback {

        @Override
        public void onStatusChanged(ConnectionStatusChangeContext connectionStatusChangeContext) {
            IotHubConnectionStatus status = connectionStatusChangeContext.getNewStatus();
            IotHubConnectionStatusChangeReason sChangeReason = connectionStatusChangeContext.getNewStatusReason();
            Throwable throwable = connectionStatusChangeContext.getCause();

            System.out.println("===== Connection =====");
            System.out.println("Status update: " + status);
            System.out.println("Status reason: " + sChangeReason);
            System.out.println("Status throwable: " + (throwable == null ? "null" : throwable.getMessage()));
            System.out.println("======================\n");

            if (throwable != null)
                throwable.printStackTrace();
            
            if (status == IotHubConnectionStatus.DISCONNECTED) {
                System.out.println("Disconnected and not retrying.");
            } else if (status == IotHubConnectionStatus.DISCONNECTED_RETRYING) {
                System.out.println("Disconnected and retrying.");
            } else if (status == IotHubConnectionStatus.CONNECTED) {
                System.out.println("Connection made.");
            }


        }
        
    }
}
